setTimeout(() => {console.log('Linea 1')},0)
setTimeout(() => {console.log('Linea 2')},2000)
console.log('linea 3')
setTimeout(() => {console.log('Linea 4')},2000)
console.log('linea 5')
console.log('linea 6')